version: '3'
services:
    neo4j:
        image: neo4j:4.4.4
        container_name: graph_db
        ports:
            - 7474:7474 # GIU
            - 7687:7687 # Web API
        expose:
            - 7474
            - 7687
        volumes:
            - ./.docker/neo4j/data:/data
            - ./.docker/neo4j/logs:/logs
            - ./.docker/neo4j/conf:/conf
        environment:
            - NEO4J_AUTH=neo4j/docker
