name: Push to Space
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  push-to-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Space shell
        shell: bash
        run: |
          curl -fsSL https://get.deta.dev/space-cli.sh | sh
          echo '/home/runner/.detaspace/bin' >> $GITHUB_PATH
          echo "SPACE_ACCESS_TOKEN=${{ secrets.SPACE_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Install pipenv
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: pipenv requirements > requirements.txt


      - name: Push
        shell: script -q -e -c "bash {0}"
        run: |
          space push --id "${{ secrets.SPACE_PROJECT_ID }}"

      - name: Release
        shell: script -q -e -c "bash {0}"
        run: |
          space release --id "${{ secrets.SPACE_PROJECT_ID }}" --confirm
